---
title: "p8105 hw6"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(mgcv)
library(modelr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2 

### Data Cleaning 

```{r}
homicide_df =
  read_csv("./data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, ", ", state),
    victim_age = as.numeric(victim_age),
    status = if_else(disposition == "Closed without arrest" | disposition == "Open/No arrest", "unresolved", "resolved"),
    status_numeric = if_else(status == "unresolved", 0, 1)
  ) %>% 
  filter(city_state != "Dallas, TX" & city_state != "Phoenix, AZ" & city_state != "Kansas, MO" & city_state != "Tusla, AL") %>% 
  filter(victim_race == "White" | victim_race == "Black")
```

### Logistic Regression Model
```{r}
logit_reg =
  homicide_df %>% 
  filter(victim_sex != "Unknown") %>% 
  glm(status_numeric ~ victim_race + victim_age + victim_sex, family = binomial(link='logit') , data = .)

logit_reg %>% 
  broom::tidy()
```

### Adjusted odds ratio 
The adjusted odds ratio of solving homicides for male victim compared to female victim is 0.603. We are 95% confident that the true odds ratio will fall into (0.569, 0.639).
```{r}
logit_reg %>% 
  broom::tidy() %>% 
  filter(term == "victim_sexMale") %>%
  mutate(
    OR = exp(estimate),
    lower_CI = exp(estimate - 1.96 * std.error),
    upper_CI = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, lower_CI, upper_CI) %>% 
  knitr::kable(digits = 3)
```




